### ISSUE TITLE
Crash while debug

### ISSUE THREAD

**Issue by FrancisToth** [ahoward/configuration#10]
Hi !

I've noticed a crash when trying to debug using this library.

``` ruby
require 'configuration'

Configuration.for('config') {
  val1 1 # <- insert a breakpoint here
}
```

The error is the following : 

```
Fast Debugger (ruby-debug-ide 0.4.23, debase 0.1.0) listens on 127.0.0.1:52955
Uncaught exception: undefined method `m' for #<Configuration:0x007f912b9fa420 @name="config">
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:78:in `method_missing'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:218:in `call'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:218:in `method_missing'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:163:in `method_missing'
    /Users/FrancisToth/Documents/Dev/repositories/git/atouch/configuration/configuration.rb:46:in `block in <top (required)>'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/debase-0.1.0/lib/debase/context.rb:7:in `eval'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/debase-0.1.0/lib/debase/context.rb:7:in `block in frame_locals'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/debase-0.1.0/lib/debase/context.rb:7:in `each'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/debase-0.1.0/lib/debase/context.rb:7:in `frame_locals'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/debase-0.1.0/lib/debase/context.rb:37:in `at_line'
    /Users/FrancisToth/Documents/Dev/repositories/git/atouch/configuration/configuration.rb:46:in `block in <top (required)>'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:218:in `instance_eval'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:218:in `call'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:218:in `method_missing'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:143:in `evaluate'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:73:in `initialize'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:34:in `new'
    /Users/FrancisToth/.rvm/gems/ruby-2.0.0-p247/gems/configuration-1.3.4/lib/configuration.rb:34:in `for'
    /Users/FrancisToth/Documents/Dev/repositories/git/atouch/configuration/configuration.rb:45:in `<top (required)>'
```

I'm using ruby 2 and intellij.

**Comment by FrancisToth** [comment]
However, if I try this : 

``` ruby
a = -> {
  'test' # insert a breakpoint here
}
Configuration.for('config') { val1 a }.val1.()
```

Everything's ok.
